### PR TITLE
Reproduce all figures, add installation instructions

### PR DESCRIPTION
**Pull request by nisheetpatel**
Made some minor changes to reproduce all figures and added installation instructions to readme

### CODE REVIEW

**Review by AlexEMG — COMMENTED** [review]
The notebooks now have your paths, I guess we want to remove those?

**Comment by nisheetpatel** [comment]
Good that you caught that. I removed the non-figure output cells from all notebooks now. I left the figures as they are.

**Comment by nisheetpatel** [comment]
Just added a notebook with code to automatically download the dataset and updated README.md to reflect that. If you'd like to check whether this works for you, run `poetry install` if you are using poetry. Otherwise `pip install requests` or `conda install requests` (since it needs the requests package) and then try running the code. I would advise switching the three instances of "datasets" (6-10GB) for "hand_reach" (~28MB) since it will be much faster.

Edit: We could change the jupyter notebook to a python script if you think that's better? I don't think it matters. I used a notebook since all other figure files are notebooks.

**Comment by albertochiappa** [comment]
Looks good to me! Maybe we can add the authors and a brief description at the beginning of the readme? Also, do we already have the bib entry of the Neuron article to replace the Biorxiv one?

**Comment by nisheetpatel** [comment]
Thanks, just added that. I think it's good to go. We won't have the Neuron link until it is published; we can update the link whenever we have it directly in the main branch

**Review by AlexEMG — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
